// <auto-generated />
using System;
using GestaoDeProdutos.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoDeProdutos.Infra.Data.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FornecedorProduto", b =>
                {
                    b.Property<int>("FornecedoresCodigo")
                        .HasColumnType("int");

                    b.Property<int>("ProdutosCodigo")
                        .HasColumnType("int");

                    b.HasKey("FornecedoresCodigo", "ProdutosCodigo");

                    b.HasIndex("ProdutosCodigo");

                    b.ToTable("FornecedorProduto");
                });

            modelBuilder.Entity("GestaoDeProdutos.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Cnpj");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.HasKey("Codigo");

                    b.ToTable("Fornecedor", (string)null);
                });

            modelBuilder.Entity("GestaoDeProdutos.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("date")
                        .HasColumnName("DataFabricacao");

                    b.Property<DateTime>("DataValidacao")
                        .HasColumnType("date")
                        .HasColumnName("DataValidacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("Situacao");

                    b.HasKey("Codigo");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("FornecedorProduto", b =>
                {
                    b.HasOne("GestaoDeProdutos.Domain.Entities.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedoresCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoDeProdutos.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
